version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  django:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.django.dev
    command: ./docker/dev/django_setup_dev.sh
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.vue.dev
    command: ./docker/dev/vue_setup_dev.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - django

volumes:
  db_data:
